export type Language = "zh" | "en"

export const languageStorageKey = "scenemint:language"
export const sizeStorageKey = "scenemint:size"
export const enhanceDirectionStorageKey = "scenemint:enhanceDirection"
export const maxReferenceSizeMB = 10
export const maxReferenceSize = maxReferenceSizeMB * 1024 * 1024

export const copy = {
  en: {
    appDescription: "Turn imagination into images",
    model: "gpt-image-2",
    language: "中文",
    relatedLinks: {
      divination: "AI Divination",
      tempMail: "Temp Mail",
    },
    promptLabel: "Image description",
    promptPlaceholder:
      "A quiet studio scene with a ceramic vase, morning light, and soft shadows",
    referenceLabel: "Reference image (optional)",
    referenceHelp: `PNG, JPEG, or WebP, up to ${maxReferenceSizeMB}MB`,
    selectReference: "Choose file",
    referenceEnabled: "Reference enabled",
    removeReference: "Remove",
    enhanceLabel: "Prompt enhancement",
    enhance: "Enhance",
    enhancing: "Enhancing",
    restorePrompt: "Restore",
    sizeLabel: "Size",
    generate: "Generate",
    preparingCredits: "Preparing credits",
    creditsUnavailable: "Credits unavailable",
    insufficientCredits: "Insufficient image credits",
    submitting: "Submitting",
    generating: "Generating",
    reusePrompt: "Reuse",
    reusePromptLabel: "Reuse prompt",
    quota: {
      unavailable: "Signature unavailable",
      remaining: "Remaining",
      checkIn: "Check in",
      retry: "Retry",
      signingIn: "Checking in",
      signed: "Signed today",
      full: "Full",
      description: (dailyGrant: number) => `Daily +${dailyGrant} credits`,
      descriptionFallback: "Daily credits",
      loadFailed: "Unable to load credits",
      fingerprintFailed: "Unable to prepare browser signature",
      checkInSuccess: (count: number) => `Checked in. ${count} credits available.`,
      alreadySigned: "Already checked in today",
      fullMessage: "Credits are full. Generate one image before checking in today.",
      noCredits: (dailyGrant: number) =>
        `Check in first to get ${dailyGrant} image credits.`,
      noCreditsFallback: "Check in first to get image credits.",
    },
    currentTitle: "Current image",
    currentEmpty: "No image yet",
    currentFailed: "Generation failed",
    currentPreview: "Open preview",
    historyTitle: "History queue",
    historyCount: (count: number) => `${count} saved locally`,
    historyRetention: "Images are kept for 7 days only",
    historyEmpty: "No history yet.",
    clearHistory: "Clear history",
    clearHistoryLabel: "Clear history",
    removeHistoryLabel: "Delete history item",
    mode: {
      image: "Image",
      text: "Text",
    },
    status: {
      queued: "Generating",
      running: "Generating",
      completed: "Ready",
      failed: "Failed",
    },
    enhanceDirections: {
      details: "Add details",
      creative: "More creative",
    },
    sizes: {
      "1:1": "Square",
      "16:9": "Landscape",
      "9:16": "Portrait",
    },
    lightbox: {
      close: "Close",
      download: "Download",
      previous: "Previous",
      next: "Next",
      zoomIn: "Zoom in",
      zoomOut: "Zoom out",
      gallery: "Image preview",
      slideCount: "{index} / {total}",
    },
    toast: {
      promptRequired: "Enter an image description",
      selectImage: "Please select an image file",
      referenceTooLarge: `Reference image must be under ${maxReferenceSizeMB}MB`,
      submitted: "Image task submitted",
      currentBusy: "Wait for the current image to finish",
      enhanceRequired: "Enter an image description before enhancing",
      enhanceFailed: "Prompt enhancement failed",
      enhancePartial: "Enhancement stopped early. You can edit the partial result.",
      enhanceEmpty: "Enhancement returned no content",
      promptReused: "Prompt reused",
    },
  },
  zh: {
    appDescription: "把想象变成画面",
    model: "gpt-image-2",
    language: "English",
    relatedLinks: {
      divination: "AI 算卦",
      tempMail: "临时邮箱",
    },
    promptLabel: "画面描述",
    promptPlaceholder: "清晨光线里的安静工作室，陶瓷花瓶，柔和阴影",
    referenceLabel: "参考图（可选）",
    referenceHelp: `PNG、JPEG 或 WebP，最大 ${maxReferenceSizeMB}MB`,
    selectReference: "选择文件",
    referenceEnabled: "已启用参考图",
    removeReference: "移除",
    enhanceLabel: "提示词增强",
    enhance: "增强",
    enhancing: "增强中",
    restorePrompt: "恢复",
    sizeLabel: "尺寸",
    generate: "生成",
    preparingCredits: "获取额度中",
    creditsUnavailable: "额度读取失败",
    insufficientCredits: "生成额度不足",
    submitting: "提交中",
    generating: "生成中",
    reusePrompt: "复用",
    reusePromptLabel: "复用提示词",
    quota: {
      unavailable: "指纹不可用",
      remaining: "剩余",
      checkIn: "签到",
      retry: "重试",
      signingIn: "签到中",
      signed: "今日已签",
      full: "额度已满",
      description: (dailyGrant: number) => `每日签到送 ${dailyGrant} 张额度`,
      descriptionFallback: "每日签到送额度",
      loadFailed: "额度读取失败",
      fingerprintFailed: "浏览器指纹准备失败",
      checkInSuccess: (count: number) => `签到成功，当前可用 ${count} 张。`,
      alreadySigned: "今天已经签到过了",
      fullMessage: "额度已满，先生成一张后今天仍可签到。",
      noCredits: (dailyGrant: number) =>
        `请先签到领取 ${dailyGrant} 张生成额度。`,
      noCreditsFallback: "请先签到领取生成额度。",
    },
    currentTitle: "当前图片",
    currentEmpty: "暂无图片",
    currentFailed: "生成失败",
    currentPreview: "打开预览",
    historyTitle: "历史记录",
    historyCount: (count: number) => `共 ${count} 条记录`,
    historyRetention: "图片仅保留 7 天",
    historyEmpty: "暂无历史记录。",
    clearHistory: "清空",
    clearHistoryLabel: "清空历史记录",
    removeHistoryLabel: "删除这条历史记录",
    mode: {
      image: "图生图",
      text: "文生图",
    },
    status: {
      queued: "生成中",
      running: "生成中",
      completed: "已完成",
      failed: "失败",
    },
    enhanceDirections: {
      details: "补充细节",
      creative: "更有创意",
    },
    sizes: {
      "1:1": "方图",
      "16:9": "横图",
      "9:16": "竖图",
    },
    lightbox: {
      close: "关闭",
      download: "下载",
      previous: "上一张",
      next: "下一张",
      zoomIn: "放大",
      zoomOut: "缩小",
      gallery: "图片预览",
      slideCount: "{index} / {total}",
    },
    toast: {
      promptRequired: "请输入画面描述",
      selectImage: "请选择图片文件",
      referenceTooLarge: `参考图不能超过 ${maxReferenceSizeMB}MB`,
      submitted: "图片任务已提交",
      currentBusy: "请等待当前图片完成",
      enhanceRequired: "请输入画面描述后再增强",
      enhanceFailed: "提示词增强失败",
      enhancePartial: "增强提前中断，可继续编辑当前结果。",
      enhanceEmpty: "增强没有返回内容",
      promptReused: "已复用提示词",
    },
  },
} as const

export type ImageGeneratorCopy = (typeof copy)[Language]

export const enhanceDirectionValues = ["details", "creative"] as const
export type EnhanceDirection = (typeof enhanceDirectionValues)[number]

export const sizeValues = ["1:1", "16:9", "9:16"] as const
